sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- 4
deploy:
  provider: script
  skip_cleanup: true
  script: npm start
  on:
    branch: master
